# Generated by Django 2.2.19 on 2023-03-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230311_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='user',
        ),
    ]
