# Generated by Django 2.2.19 on 2023-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230313_1702'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subscriber_author_uniqueness',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'user'), name='subscriber_author_uniqueness'),
        ),
    ]
